;; This file is automatically generated *.in file.
;; Do not modify this file - YOUR CHANGES WILL BE ERASED!
;; You can edit *.in file and 'autoconf && ./configure'
;; このファイルは *.in ファイルから自動生成されました。
;; このファイルは変更しないで下さい。
;; 代わりに *.in を変更し、 'autoconf && ./configure' して下さい。

;; this is dummy project to make texture atlas

(defproject
  texture-packer2 "0.0.0"
  ;:description "FIXME: write description"
  ;:url "http://example.com/FIXME"
  ;:license {:name "Eclipse Public License"
  ;          :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.5.0"]
                 [com.badlogic.gdx/gdx "0.9.8"]
                 [com.badlogic.gdx/gdx-tools "0.9.8"]
                 ]
  :source-paths []
  :java-source-paths []
  :test-paths []
  :resource-paths []
  :plugins []
  )

