language: clojure
#install: mkdir -p tmp_travis && cd tmp_travis && ln -sf ../../clan clan && sh clan/script/spread_current_dir.sh && autoconf && ./configure && make release-jar && cd ..
install: cd .. && sh clan/script/spread_current_dir.sh && autoconf && ./configure && make release-jar && make android-apk && cd clan
script: test -e ../target/drop.jar && test -e ../android/target/drop-debug.apk && echo OK
lein: lein2
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
before_install:
  # came from http://shunirr.hatenablog.jp/entry/2013/04/02/141846
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # http://developer.android.com/sdk/index.html
  - wget http://dl.google.com/android/android-sdk_r22.0.5-linux.tgz
  - tar xvzf android-sdk_r22.0.5-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
    #- android list sdk
  - android update sdk --filter platform-tools,android-9 --no-ui --force
  - ls ${ANDROID_HOME}/platforms
