language: clojure
#install: mkdir -p tmp_travis && cd tmp_travis && ln -sf ../../clan clan && sh clan/script/spread_current_dir.sh && autoconf && ./configure && make release-jar && cd ..
install: cd .. && sh clan/script/spread_current_dir.sh && autoconf && ./configure && make release-jar && cd clan
script: test -e ../target/drop.jar && echo OK
lein: lein2
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
