language: clojure
#install: mkdir -p tmp_travis && cd tmp_travis && ln -sf ../../clan clan && sh clan/script/spread_current_dir.sh && autoconf && ./configure && make release-jar && cd ..
install: cd .. && sh clan/script/spread_current_dir.sh && autoconf && ./configure && make release-jar && make android-apk && cd clan
script: test -e ../target/drop.jar && test -e ../android/target/drop-debug.apk && echo OK
lein: lein2
jdk:
  - openjdk6
  # - openjdk7
  # - oraclejdk7
  # TODO: enable Java 7 and only build apk with Java 6, without Java 7
before_install:
  # came from http://shunirr.hatenablog.jp/entry/2013/04/02/141846
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # http://developer.android.com/sdk/index.html
  - export ANDROID_SDK_VERSION=r21.1
  - wget http://dl.google.com/android/android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - tar xvzf android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
  - android list sdk --extended -a
  - android update sdk --no-ui --force --filter "tools,platform-tools,build-tools-17.0.0,android-9,android-17"
