language: clojure
lein: lein2
install:
  - cd ..
  - sh clan/script/spread_current_dir.sh
  - autoconf
  - ./configure
  - make release-jar
  - if (javac -version 2>&1 | grep '^javac 1\.6'); then make android-apk; fi
  - cd clan
script:
  - test -e ../target/drop.jar
  - if (javac -version 2>&1 | grep '^javac 1\.6'); then test -e ../android/target/drop-debug.apk; fi
  # TODO: must be write test
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
before_install:
  - if (javac -version 2>&1 | grep '^javac 1\.6'); then
  # came from http://shunirr.hatenablog.jp/entry/2013/04/02/141846
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # http://developer.android.com/sdk/index.html
  - export ANDROID_SDK_VERSION=r21.1
  - wget http://dl.google.com/android/android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - tar xvzf android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
  - android list sdk --extended -a
  - android update sdk --no-ui --force --filter tools,platform-tools,build-tools-17.0.0,android-18,android-17,android-10,extra-android-m2repository,extra-android-support
  - fi

# vim:set sw=2 ts=2 sts=2 et:
